import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import AuthProviders from "../components/AuthProviders";
import DynamicBackground from "../components/DynamicBackground"; // Import DynamicBackground

const roboto = Roboto({
  weight: ["300", "400", "500", "700"],
  subsets: ["latin"],
  variable: "--font-roboto",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${roboto.variable} font-sans antialiased`}>
        <DynamicBackground /> {/* Render DynamicBackground here */}
        <AuthProviders>{children}</AuthProviders>
      </body>
    </html>
  );
}
